services:
  # Combined Frontend + Backend Service
  - type: web
    name: invguard-app
    runtime: docker
    dockerfilePath: ./dockerfile
    dockerContext: ./
    region: oregon
    plan: starter
    envVars:
      - key: JWT_SECRET_KEY
        value: e71314edcad5068330de2317e21598d88af7704f5433481d0500493f1d631013
      - key: GPG_PASSPHRASE
        value: qpxjp2ptN4-Rq-QIBF_0qD9hsU2HWVQHyG7b30a7y5Y
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_PATH
        value: /data/inventory.db
      - key: BACKUP_PATH
        value: /backups
      - key: BACKUP_RETENTION_DAYS
        value: "30"
      - key: HEALTH_CHECK_INTERVAL
        value: "300"
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: "5000"
    disk:
      name: invguard-database
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /api/health

  # Cron Job Service (kept)
  - type: worker
    name: invguard-cron
    runtime: docker
    dockerfilePath: ./cron/Dockerfile
    dockerContext: ./cron
    region: oregon
    plan: starter
    envVars:
      - key: DATABASE_PATH
        value: /data/inventory.db
      - key: BACKUP_PATH
        value: /backups
      - key: GPG_PASSPHRASE
        sync: false
      - key: API_URL
        value: https://invguard-backend.onrender.com/api
      - key: BACKUP_RETENTION_DAYS
        value: 30
      - key: HEALTH_CHECK_INTERVAL
        value: 300
    disk:
      name: invguard-backups
      mountPath: /backups
      sizeGB: 2
