apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invguard-db-pvc
  namespace: invguard
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invguard-backup-pvc
  namespace: invguard
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
